---
title: "Analiza političarki"
author: "Tiana"
date: '10 06 2022 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r libs, include=TRUE, echo=FALSE,message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(kableExtra)
library(DT)
library(data.table)
library(lubridate)
library(anytime)
library(tidytext)
library(grid)
library(wordcloud)
library(reshape2)
library(ggraph)
library(widyr)
library(topicmodels)
library(ggthemes)
library(report)
library(dplyr)
```

```{r, echo=FALSE}
path <- "C:/Users/Admin/OneDrive/Desktop"
```

```{r , echo=FALSE}
raw <- list.files(path = path , pattern="xlsx")
raw_path <- paste0(path, "/", raw)
all_raw <- map_df(raw_path, read_excel)

all <- as.data.table(all_raw)
all <- all[,DATE := as.Date(DATE,"%Y-%m-%d")][,DATETIME := anytime(paste(DATE,TIME))]
posts <- all


# some basic data overview
options(digits = 2)
# data size 
dim(posts)
# time span
range(posts$DATETIME)
```

## Deskriptivna statistika 
### Broj podataka i broj varijabli

```{r, collapse=TRUE}
 posts[,.N,SOURCE_TYPE][order(-N)]
```

### Broj slova u naslovu
```{r, collapse=TRUE}

posts[,
       .(Avg = mean(nchar(TITLE), na.rm = T),
         STD = sd(nchar(TITLE), na.rm = T),
         min = min(nchar(TITLE), na.rm = T),
         max = max(nchar(TITLE), na.rm = T)),
      SOURCE_TYPE][order(-Avg),]
```

### Broj slova u tekstu
```{r, collapse=TRUE}

posts[,
       .(Avg = mean(nchar(FULL_TEXT)),
         STD = sd(nchar(FULL_TEXT)),
         min = min(nchar(FULL_TEXT)),
         max = max(nchar(FULL_TEXT))),
      SOURCE_TYPE][order(-Avg),]

```



```{r leksikoni, echo=FALSE, message=F, warning=F}
# read in lexicons
CroSentilex_n <- read.delim("C:/Users/Admin/OneDrive/Desktop/crosentilex-negatives.txt",
                                   header = FALSE,
                                   sep = " ",
                                   stringsAsFactors = FALSE,
                                   fileEncoding = "UTF-8")  %>%
                   rename(word = "V1", sentiment = "V2" ) %>%
                   mutate(brija = "NEG")
 
CroSentilex_p  <- read.delim("C:/Users/Admin/OneDrive/Desktop/crosentilex-positives.txt",
                                   header = FALSE,
                                   sep = " ",
                                   stringsAsFactors = FALSE,
                                   fileEncoding = "UTF-8") %>%
                    rename(word = "V1", sentiment = "V2" ) %>%
                    mutate(brija = "POZ")
 
Crosentilex_sve <- rbind(setDT(CroSentilex_n), setDT(CroSentilex_p))

head(sample_n(Crosentilex_sve,1000),15)
 
CroSentilex_Gold  <- read.delim2("C:/Users/Admin/OneDrive/Desktop/crosentilex-gold.txt",
                                 header = FALSE,
                                 sep = " ",
                                 stringsAsFactors = FALSE) %>%
                    rename(word = "V1", sentiment = "V2" ) 
 Encoding(CroSentilex_Gold$word) <- "UTF-8"
 CroSentilex_Gold[1,1] <- "dati"
 CroSentilex_Gold$sentiment <- str_replace(CroSentilex_Gold$sentiment , "-", "1")
 CroSentilex_Gold$sentiment <- str_replace(CroSentilex_Gold$sentiment , "\\+", "2")
 CroSentilex_Gold$sentiment <- as.numeric(unlist(CroSentilex_Gold$sentiment))
# check lexicon data 
head(sample_n(CroSentilex_Gold,100),15)


 
# create stop words
stopwords_cro <- get_stopwords(language = "hr", source = "stopwords-iso")

# check stopwords data
head(sample_n(stopwords_cro,100),15)
# extend stop words
my_stop_words <- tibble(
  word = c(
    "jedan","mjera", "može", "mogu", "kad", "sada", "treba", "ima", "osoba",
    "e","prvi", "dva","dvije","drugi",
    "tri","treći","pet","kod",
    "ove","ova",  "ovo","bez", "kod",
    "evo","oko",  "om", "ek",
    "mil","tko","šest", "sedam",
    "osam",   "čim", "zbog",
    "prema", "dok","zato", "koji", 
    "im", "čak","među", "tek",
    "koliko", "tko","kod","poput", 
    "baš", "dakle", "osim", "svih", 
    "svoju", "odnosno", "gdje",
    "kojoj", "ovi", "toga",
     "ubera", "vozača", "hrvatskoj", "usluge", "godine", "više", "taksi", "taxi", "taksija", "taksija", "kaže", "rekao", "19"," aee", "ae"
  ),
  lexicon = "lux"
)
stop_corpus <- my_stop_words %>%
  bind_rows(stopwords_cro)
# check stopwords data
head(sample_n(stop_corpus,100),15)
```

```{r, echo=FALSE}
raw <- list.files(path = path , pattern="xlsx")
raw_path <- paste0(path, "/", raw)
all_raw <- map_df(raw_path, read_excel)

all <- as.data.table(all_raw)
all <- all[,DATE := as.Date(DATE,"%Y-%m-%d")][,DATETIME := anytime(paste(DATE,TIME))]
posts <- all
```

```{r, echo=FALSE}
web <- posts[SOURCE_TYPE == "web",]
#pofb <- posts[SOURCE_TYPE == "facebook",]
#youtube <- posts[SOURCE_TYPE == "youtube",]
#instagram <- posts[SOURCE_TYPE == "instagram",]
#twitter <- posts[SOURCE_TYPE == "twitter",]
#reddit <- posts[SOURCE_TYPE == "reddit",]
#forum <-  posts[SOURCE_TYPE == "forum",]
#comment <-  posts[SOURCE_TYPE == "comment",]
```

```{r, eval=T, collapse=TRUE}
## Portali prema aktivnosti
print(web[,.N,FROM][order(-N)], big.mark=",")

## Portali prema "dosegu"
print(unique(web[,REACH := sum(REACH), FROM][FROM != "anonymous_user",.(FROM,REACH)][order(-REACH),]), big.mark=",")

## Portali prema lajkovima  
print(unique(web[,LIKE := sum(LIKE_COUNT), FROM][FROM != "anonymous_user",.(FROM,LIKE)][order(-LIKE),]), big.mark=",")

## Portali prema interakcijama
print(unique(web[,INTERACTIONS := sum(INTERACTIONS), FROM][FROM != "anonymous_user",.(FROM,INTERACTIONS)][order(-INTERACTIONS),]), big.mark=",")

# Portali prema komentarima 
print(unique(web[,COMMENT := sum(COMMENT_COUNT), FROM][FROM != "anonymous_user",.(FROM,COMMENT)][order(-COMMENT),]), big.mark=",")
```

```{r}
# dim before tokenize
dim(web)
# tokenize
web %>% 
  unnest_tokens(word, FULL_TEXT) -> web
# dim after tokenize
dim(web)
# check
web %>% 
  sample_n(.,5)
```

```{r}
# remove stop words, numbers, single letters, NA
web %>% 
  anti_join(stop_corpus, by = "word") %>%
  mutate(word = gsub("\\d+", NA, word)) %>%
  mutate(word = gsub("^[a-zA-Z]$", NA, word)) -> web_tokenTidy

web_tokenTidy %>%
  filter(!is.na(word)) -> web_tokenTidy
# check
web_tokenTidy %>%
  sample_n(.,5) %>%
  datatable(., rownames = FALSE, options = list(pageLength = 5, scrollX=T))
```

``` {r}
# remove stop words, numbers, single letters, NA
web %>% 
  anti_join(stop_corpus, by = "word") %>%
  mutate(word = gsub("\\d+", NA, word)) %>%
  mutate(word = gsub("^[a-zA-Z]$", NA, word)) -> web_tokenTidy
web_tokenTidy %>%
  filter(!is.na(word)) -> web_tokenTidy
# check
web_tokenTidy %>%
  sample_n(.,5) %>%
  datatable(., rownames = FALSE, options = list(pageLength = 5, scrollX=T))
```

# ANALYSE


### BASIC FREQUENCIES
```{r}
## Most common words
print(web_tokenTidy[,.N,by = word][order(-N),][N > 1500], big.mark=",")
## Vizualize most common words
web_tokenTidy[,.N,by = word][N>1500][order(-N),][,word := reorder(word,N)] %>%
  ggplot(aes(word, N)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  theme_economist()

```

```{r}
## Articles per domain over time
web_tokenTidy %>% 
   filter(word == "hdz" & FROM %in% c("direktno.hr", "hrt.hr", "glasistre.hr")) %>%
   mutate(WEEK = floor_date(DATE, "week")) %>%
   group_by(WEEK, FROM) %>%
   summarise(n = n()) %>%
   ungroup() %>%
   arrange(desc(n)) %>%
   ggplot(., aes(WEEK,  n)) + 
   geom_line() +
   ggtitle("Korištenje riječi HDZ u člancima o Selak Raspudić i Benčić kroz vrijeme") +
   ylab("Broj objava") +
   geom_smooth() +
   facet_wrap(~ FROM, scales = "free_y") +
   theme_economist()
```
```{r}
## Articles per domain over time
web_tokenTidy %>% 
   filter(word == "sdp" & FROM %in% c("direktno.hr", "hrt.hr", "glasistre.hr")) %>%
   mutate(WEEK = floor_date(DATE, "week")) %>%
   group_by(WEEK, FROM) %>%
   summarise(n = n()) %>%
   ungroup() %>%
   arrange(desc(n)) %>%
   ggplot(., aes(WEEK,  n)) + 
   geom_line() +
   ggtitle("Korištenje riječi SDP u člancima o Selak Raspudić i Benčić kroz vrijeme") +
   ylab("Broj objava") +
   geom_smooth() +
   facet_wrap(~ FROM, scales = "free_y") +
   theme_economist()
```

```{r}
## Articles per domain over time
web_tokenTidy %>% 
   filter(word == "most" & FROM %in% c("direktno.hr", "hrt.hr", "glasistre.hr")) %>%
   mutate(WEEK = floor_date(DATE, "week")) %>%
   group_by(WEEK, FROM) %>%
   summarise(n = n()) %>%
   ungroup() %>%
   arrange(desc(n)) %>%
   ggplot(., aes(WEEK,  n)) + 
   geom_line() +
   ggtitle("Korištenje riječi most u člancima o Selak Raspudić i Benčić kroz vrijeme") +
   ylab("Broj objava") +
   geom_smooth() +
   facet_wrap(~ FROM, scales = "free_y") +
   theme_economist()
```
### SENTIMENT

```{r sentimentTempus, message=F, warning=F}
## Sentiment over time
vizualiziraj_sentiment <- function(dataset, frq = "week") {
dataset %>%
  inner_join( Crosentilex_sve, by = "word") %>%
  filter(!is.na(word)) %>%
  select(word, brija, DATE, sentiment) %>% 
  unique() %>%
  spread(. , brija, sentiment) %>%
  mutate(sentiment = POZ - NEG) %>%
  select(word, DATE, sentiment) %>% 
  group_by(word) %>% 
  mutate(count = n()) %>%
  arrange(desc(count)) %>%
  mutate( score = sentiment*count) %>%
  ungroup() %>%
  group_by(DATE) %>%
  arrange(desc(DATE)) -> sm
 
sm %>%
  select(DATE, score) %>%
  group_by(DATE = floor_date(DATE, frq)) %>%
  summarise(Dnevni_sent = sum(score, na.rm = TRUE)) %>%
  ggplot(., aes(DATE, Dnevni_sent)) +
  geom_bar(stat = "identity") + 
  ggtitle(paste0("Frekvencija sentomenta kroz vrijeme:", frq)) +
  ylab("SentimentScore") +
  theme_economist()-> gg_sentiment_kroz_vrijeme_qv
gg_sentiment_kroz_vrijeme_qv
}
vizualiziraj_sentiment(web_tokenTidy,"week")
```



```{r doprinoSentimentu, message=F, warning=F, fig.width=10}
## Sentiment 
doprinos_sentimentu <- function(dataset, no = n) {
dataset %>%
  inner_join(CroSentilex_Gold, by = "word") %>% 
  count(word, sentiment,sort = TRUE) %>% 
  group_by(sentiment) %>%
  top_n(no) %>%
  ungroup() %>%
  mutate(sentiment = case_when(sentiment == 0 ~ "NEUTRAL",
                                 sentiment == 1 ~ "NEGATIVE",
                                 sentiment == 2 ~ "POSITIVE")) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  ggtitle( "Sentiment") +
  labs( x = "Riječ", y = "Number of words") +
  facet_wrap(~ sentiment, scales = "free_y") +
  coord_flip() +
  theme_economist() -> gg_doprinos_sentimentu
  
 gg_doprinos_sentimentu
 
}
doprinos_sentimentu(web_tokenTidy,15)
```

Simple WordCloud:

```{r WCloud, message=F, warning=F}
## WordCloud(vulgaris)
web_tokenTidy %>%
  anti_join(CroSentilex_Gold,by="word") %>% 
  count(word) %>% 
  arrange(desc(n)) %>%
  top_n(100) %>%
  with(wordcloud(word, n, max.words = 100)) 
```

WordCloud sentimenta:

```{r WCloutSent, warning=F, message=F}
## ComparisonCloud
web_tokenTidy %>%
  inner_join(CroSentilex_Gold,by="word") %>% 
  count(word, sentiment) %>% 
  top_n(200) %>%
  mutate(sentiment = case_when(sentiment == 0 ~ "+/-",
                                 sentiment == 1 ~ "-",
                                 sentiment == 2 ~ "+")) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("firebrick3", "deepskyblue3","darkslategray"),
                   max.words = 120)
```


Negativity analysis of influencers:

```{r negDomen, warning=F, message=F}
## Najnegativniji portali
wCount <- web_tokenTidy %>% 
  group_by(FROM) %>%
  summarise(word = n())
CroSentilex_Gold_neg <- CroSentilex_Gold %>% filter(sentiment == 1)
CroSentilex_Gold_poz <- CroSentilex_Gold %>% filter(sentiment == 2)
web_tokenTidy %>% 
  semi_join(CroSentilex_Gold_neg, by= "word") %>%
  group_by(FROM) %>% 
  summarise(negWords = n()) %>%
  left_join(wCount, by = "FROM") %>%
  mutate(negativnostIndex = (negWords/word)*100) %>%
  arrange(desc(negativnostIndex)) %>%
  print(., big.mark=",")
```

...also positivity:

```{r pozDomen, warning=F, message=F}
## Najpozitivniji portali
CroSentilex_Gold_poz <- CroSentilex_Gold %>% filter(sentiment == 2)
web_tokenTidy %>% 
  semi_join(CroSentilex_Gold_poz, by= "word") %>%
  group_by(FROM) %>% 
  summarise(pozWords = n()) %>%
  left_join(wCount, by = "FROM") %>%
  mutate(pozitivnostIndex = (pozWords/word)*100) %>%
  arrange(desc(pozitivnostIndex)) %>%
  print(., big.mark=",") 
```


### TERM IMPORTANCE



```{r frekvencija, message=F, warning=F, fig.height=10, fig.width=10}
## Udio riječi po domenama
domenaWords <- web_tokenTidy %>%
  filter(FROM %in% c("direktno.hr", "hrt.hr", "glasistre.hr" )) %>% 
  count(FROM, word, sort = T)
  
ukupnoWords <- domenaWords %>%
  group_by(FROM) %>%
  summarise(totWords = sum(n))
domenaWords <- left_join(domenaWords, ukupnoWords)
# domenaWords %>% head(15)
# domenaWords %>% 
# ggplot(., aes(n/totWords, fill = domena)) +
#   geom_histogram(show.legend = FALSE) +
#   xlim(NA, 0.0009) +
#   facet_wrap(~domena, ncol = 2, scales = "free_y")
## Najbitnije riječi po domenma
idf <- domenaWords %>%
  bind_tf_idf(word, FROM, n)
idf %>% head(10)
# idf %>% 
#   select(-totWords) %>%
#   arrange(desc(tf_idf))
idf %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  mutate(FROM = factor(FROM)) %>%
  group_by(FROM) %>% 
  top_n(15) %>% 
  ungroup() %>%
  ggplot(aes(word, tf_idf, fill = FROM)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~FROM, ncol = 2, scales = "free") +
  coord_flip() +
  theme_economist()
```

